### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by keveri** [jkpl/neljas#2]
Ability to send pdf file as an email attachment

**Comment by jkpl** [comment]
This is a good library for that: https://commons.apache.org/proper/commons-email/

**Comment by keveri** [comment]
Probably related: https://gist.github.com/mariussoutier/3436111

**Comment by jkpl** [comment]
That looks pretty over engineered, and it doesn't handle configuration. Java style is just fine since it can be encapsulated under a single class/object. :)
